### ISSUE TITLE
Naming convention of piece sets

### ISSUE THREAD

**Issue by tsoj** [kmar/livius#10]
It seems like the naming convention for piece sets for Lichess is the same as for Livius, except that for Lichess the letter for the piece type is always upper case (e.g Lichess: bB.svg, wN.svg, ... Livius: bb.svg, wn.svg). To make the usage of the [many Lichess svg piece sets](https://github.com/ornicar/lila/tree/master/public/piece) easier in Livius I would suggest to adopt this naming standard. If that's okay, I would create a pull request.

**Comment by kmar** [comment]
done - now using a lichess naming convention as a fallback, so old naming convention will work as well
