### ISSUE TITLE
Problems with ipv6 (IPv4 over DS-Lite)

### ISSUE THREAD

**Issue by philipp-classen** [kmar/livius#5]
I fail to connect when I'm behind an ipv6 internet connection. Though livius on my Linux notebook worked fine behind a ipv4 connection, it fails to connect when I'm connected via ipv6. I seem to be able to connect but I'm immediately logged out. Other people saw my entering and leaving the chat repeatedly. I did not debug into it, because it spams the chat and is annoying for the other users.

I have seen some recent fixes for ipv6, so I wonder if it is a configuration problem in my environment. My provider is M-Net. It uses IPv4 over DS-Lite (Dual-Stack Lite). Maybe that makes a difference, but my knowledge about ipv6 is not deep enough.

Not sure if it is a bug but I wanted to report it, so other people that run into the same problem can comment. With ipv6, using Tom's Live Chess Viewer on Windows also does not work for me.

**Comment by kmar** [comment]
Sorry for the late reply Phillip. Unfortunately I've IPv4 here and so I'm unable to help out. Maybe you could find a broadcast without connected people (or at some exotic time) where you could perhaps try to debug? I'd of course accept a patch if you'd manage to solve a problem, unless as you said it's some configuration problem of yours.

**Comment by philipp-classen** [comment]
I added some debug messages. From what I see, TLCVClient::connectTo successfully sends out an UDP packet with "LOGONv15:Anonymous". At least client->send inside TLCVClient::send returns true.

That is consistent with the observation that the login partly works. However, I never see the receive methods getting any data. Eventually, after the 10 second timeout, TLCVClient::refresh gives up and "sigConnectionError(ERR_CONNFAILED);" is triggered.

Looks like the messages from the server do not arrive. Just to be sure, you do not have to open any ports as the client? After sending "LOGONv15", what would normally be the next step in the protocol?

**Comment by kmar** [comment]
Yes, to be able to receive UDP packets you have to open ports (firewall/router).

**Comment by philipp-classen** [comment]
I figured it out. It is definitely DS-Lite. On the plus side, it is not a problem in livius.

This is my understanding of DS-Lite. I have a public ipv6 address and can establish connection to other ipv6 connected machine (in both directions). In addition, DS-Lite (Dual-Stack Lite) allows to establish outgoing ipv4 connections from my machine to another ipv4 machine. This is implemented by tunneling over my provider, which establishes the ipv4 connection.

The drawback of DS-Lite is that the other way around is, unfortunately, not supported. That is why it is called "Lite".

```
phil@amd8-arch:~$ ping -4 GrahamCCRL.dyndns.org
PING GrahamCCRL.dyndns.org (222.154.252.101) 56(84) bytes of data.

phil@amd8-arch:~$ ping -6 GrahamCCRL.dyndns.org
ping: GrahamCCRL.dyndns.org: Name or service not known
```
That shows that the server uses ipv4 and explains why the connection cannot be established.

For others that run into the same problem (DS-Lite is becoming more common, at least, in Germany), there is not much that you can do. I read about relays that you can buy, which seem to work similar to tunneling done by the provider but in the other direction. Or wait until everything is ipv6. :-)

Anyway, I think we can safely close this one.
